package net.inokinn.naroreader

data class Novel (
    val title: String,
    val ncode: String,
    val userid: Int,
    val writer: String,
    val story: String,
    val biggenre: Int,
    val genre: Int,
    val gensaku: String,
    val keyword: String,
    val general_firstup: String,
    val general_lastup: String,
    val novel_type: Int,
    val end: Int,
    val general_all_no: Int,
    val length: Int,
    val time: Int,
    val isstop: Int,
    val isr15: Int,
    val isbl: Int,
    val isgl: Int,
    val iszankoku: Int,
    val istensei: Int,
    val isTenni: Int,
    val pc_or_k: Int,
    val global_point: Int,
    val daily_point: Int,
    val weekly_point: Int,
    val monthly_point: Int,
    val quarter_point: Int,
    val yearly_point: Int,
    val fav_novel_cnt: Int,
    val impression_cnt: Int,
    val review_cnt: Int,
    val all_point: Int,
    val all_hyoka_cnt: Int,
    val sasie_count: Int,
    val kaiwaritu: Int,
    val novelupdated_at: String,
    val updated_at: String
)